lib: [
  "_build/install/default/lib/bisect_ppx-ocamlbuild/META" {"META"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/opam" {"opam"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_plugin.cmi"
    {"bisect_ppx_plugin.cmi"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_plugin.cmx"
    {"bisect_ppx_plugin.cmx"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_plugin.cmt"
    {"bisect_ppx_plugin.cmt"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_plugin.cmti"
    {"bisect_ppx_plugin.cmti"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_plugin.mli"
    {"bisect_ppx_plugin.mli"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_plugin.ml"
    {"bisect_ppx_plugin.ml"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_ocamlbuild.cma"
    {"bisect_ppx_ocamlbuild.cma"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_ocamlbuild.cmxa"
    {"bisect_ppx_ocamlbuild.cmxa"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_ocamlbuild.a"
    {"bisect_ppx_ocamlbuild.a"}
  "_build/install/default/lib/bisect_ppx-ocamlbuild/bisect_ppx_ocamlbuild.cmxs"
    {"bisect_ppx_ocamlbuild.cmxs"}
]
doc: [
  "_build/install/default/doc/bisect_ppx-ocamlbuild/README.md"
  "_build/install/default/doc/bisect_ppx-ocamlbuild/LICENSE"
]
